import React, { useState } from 'react';
import Header from './components/Header';
import FileUpload from './components/FileUpload';
import AnalysisResultDisplay from './components/AnalysisResultDisplay';
import AuthModal from './components/AuthModal';
import { AnalysisResult, UserProfile } from './types';
import { analyzeMedicalImage } from './services/geminiService';
import { Loader2 } from 'lucide-react';

const App: React.FC = () => {
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysisResult, setAnalysisResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  
  // Global User State
  const [currentUser, setCurrentUser] = useState<UserProfile | null>(null);
  const [isAuthModalOpen, setIsAuthModalOpen] = useState(false);

  const handleAnalyze = async (file: File) => {
    setIsAnalyzing(true);
    setError(null);
    setAnalysisResult(null);

    try {
      // Convert file to base64
      const reader = new FileReader();
      reader.onloadend = async () => {
        const base64String = reader.result as string;
        const base64Data = base64String.split(',')[1];
        
        try {
          const result = await analyzeMedicalImage(base64Data, file.type);
          setAnalysisResult(result);
        } catch (err) {
            console.error(err);
            setError("Failed to analyze the image. Please try again or check your API key.");
        } finally {
          setIsAnalyzing(false);
        }
      };
      
      reader.onerror = () => {
          setError("Failed to read the file.");
          setIsAnalyzing(false);
      }
      
      reader.readAsDataURL(file);
    } catch (err) {
      setError("An unexpected error occurred.");
      setIsAnalyzing(false);
    }
  };

  const handleLogin = (user: UserProfile) => {
    setCurrentUser(user);
    setIsAuthModalOpen(false);
  };

  const handleLogout = () => {
    setCurrentUser(null);
    setIsAuthModalOpen(false);
    setAnalysisResult(null);
  };

  const handleViewReport = (result: AnalysisResult) => {
    setAnalysisResult(result);
    setIsAuthModalOpen(false);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans selection:bg-teal-100 selection:text-teal-900">
      <Header 
        user={currentUser} 
        onOpenProfile={() => setIsAuthModalOpen(true)} 
      />
      
      <main className="max-w-5xl mx-auto px-4 py-8 md:py-12">
        <section className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-extrabold text-slate-800 mb-4 tracking-tight">
            Understand Your <span className="text-teal-600">Health Data</span> Instantly
          </h2>
          <p className="text-lg text-slate-600 max-w-2xl mx-auto">
            Upload a photo of your lab report or prescription. MediLens extracts the data, explains the medical jargon, and gives you actionable insights.
          </p>
        </section>

        <FileUpload onAnalyze={handleAnalyze} isAnalyzing={isAnalyzing} />

        {error && (
            <div className="max-w-2xl mx-auto mb-8 p-4 bg-red-50 text-red-700 rounded-lg border border-red-200 text-center">
                {error}
            </div>
        )}

        {isAnalyzing && (
            <div className="text-center py-12 animate-pulse">
                <div className="inline-block p-4 bg-white rounded-full shadow-lg mb-4">
                     <Loader2 className="animate-spin text-teal-600 w-8 h-8" />
                </div>
                <h3 className="text-xl font-semibold text-slate-700">Analyzing Document...</h3>
                <p className="text-slate-500">Extracting values and generating interpretations</p>
            </div>
        )}

        {analysisResult && (
            <AnalysisResultDisplay 
              result={analysisResult} 
              user={currentUser}
              onLoginRequest={() => setIsAuthModalOpen(true)}
            />
        )}
      </main>

      <AuthModal 
        isOpen={isAuthModalOpen} 
        onClose={() => setIsAuthModalOpen(false)}
        user={currentUser}
        onLogin={handleLogin}
        onLogout={handleLogout}
        onViewReport={handleViewReport}
      />

      <footer className="bg-white border-t border-slate-200 py-8 mt-12">
        <div className="max-w-5xl mx-auto px-4 text-center text-slate-400 text-sm">
          <p>&copy; {new Date().getFullYear()} MediLens AI. All rights reserved.</p>
          <p className="mt-2 max-w-lg mx-auto">
            Disclaimer: Not a medical device. Results are generated by AI and may contain errors. Always consult a certified medical professional.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default App;
